### ISSUE TITLE
add an option to read data from a websocket source

### ISSUE THREAD

**Issue by digikata** [infinyon/http-source-connector#142]
The http-source-connector can read data in many forms over http protocols to be produced into a fluvio cluster. But it doesn't understand websockets.

Add the option to read websockets to the connector..

Other open-source users have built a nice prototype: https://github.com/mrasputin/fluvio-websocket-source-connector

Integrating the feature with this connector would allow for a standardized way of accessing http sources (e.g. with features alike being able to supply api keys to the external source).

**Comment by avikam** [comment]
Hi @digikata , I refactored the reference implementation to use async streams rather than channels.
not sure if someone was picking it up, but if the approach is sound to you i'm happy to port it to this connector as a sibling of http-streaming-source and http-source.

refactor:
https://github.com/avikam/fluvio-websocket-source-connector/blob/main/src/source.rs

**Comment by sehz** [comment]
Nice refactoring.  We should try to merge this

**Comment by avikam** [comment]
sg @sehz . i made another pass, aligning the project structure to use crates and added a similar [test file](https://github.com/avikam/fluvio-websocket-source-connector/blob/main/tests/websocket-test.bats) to ease the merge.
